#!/bin/bash

set -v

# Check Kubernetes version
kubectl version --short | grep server -i

# Check Istio version by looking at the image version
kubectl get pod -l app=istio-ingressgateway -n istio-system -oyaml | grep istio/proxyv2 -m 1

# Check Knative Serving version
kubectl get namespace knative-serving -o 'go-template={{index .metadata.labels "serving.knative.dev/release"}}'

# Check Knative Eventing version
kubectl get namespace knative-eventing -o 'go-template={{index .metadata.labels "eventing.knative.dev/release"}}'

# Check Knative-GCP version
kubectl get namespace cloud-run-events -o 'go-template={{index .metadata.labels "events.cloud.google.com/release"}}'

# Check Tekton version
kubectl get pod -l app=tekton-pipelines-controller -n tekton-pipelines -o jsonpath='{.items[*].metadata.labels.version}'