#!/bin/bash

export KNATIVE_SERVING_VERSION="0.21.0"

export KNATIVE_EVENTING_VERSION="0.21.1"

export PROJECT_ID="knative-atamel"

export CLUSTER_NAME="knative-021"

export CLUSTER_REGION="europe-west1"

export CLUSTER_ZONE="${CLUSTER_REGION}-b"

export CLUSTER_START_NODE_SIZE=3

export CLUSTER_MAX_NODE_SIZE=10

export CLUSTER_NODE_MACHINE_TYPE="n1-standard-4"

export CLUSTER_MASTER_VERSION="latest"