#!/bin/bash

export CLUSTER_NAME="knative"

export CLUSTER_REGION="europe-west1"

export CLUSTER_ZONE="${CLUSTER_REGION}-b"

# initial cluster size
export CLUSTER_START_NODE_SIZE=3

# max cluster size
export CLUSTER_MAX_NODE_SIZE=10

# the type of VM used for worker nodes
export CLUSTER_NODE_MACHINE_TYPE="n1-standard-4"

# version of kubernetes
export CLUSTER_MASTER_VERSION="latest"

# knative version
export KN_VERSION="v0.11.0"