#!/bin/bash

DIR="$(dirname "$0")"
. "${DIR}/config"

set -v

# Doc:
# https://github.com/google/knative-gcp/blob/master/docs/install/dataplane-service-account.md

# Enable the Cloud Pub/Sub API on your project:
gcloud services enable pubsub.googleapis.com

# Create a new Service Account named
gcloud iam service-accounts create cre-dataplane

# Give that Service Account the necessary permissions
# Note: You probably need something more fine-grained than roles/pubsub.editor
gcloud projects add-iam-policy-binding ${PROJECT_ID} \
  --member=serviceAccount:cre-dataplane@${PROJECT_ID}.iam.gserviceaccount.com \
  --role roles/pubsub.editor

if [ "$1" == "workload" ]; then
  gcloud iam service-accounts add-iam-policy-binding \
    cre-dataplane@${PROJECT_ID}.iam.gserviceaccount.com \
    --member=serviceAccount:cloud-run-events@${PROJECT_ID}.iam.gserviceaccount.com \
    --role=roles/iam.serviceAccountAdmin
  echo "Note: You need to manually modify clusterDefaults in ConfigMap config-gcp-auth, as described in the docs."
else
  # Download a new JSON private key for that Service Account
  # Be sure not to check this key into source control!
  gcloud iam service-accounts keys create cre-dataplane.json \
  --iam-account=cre-dataplane@${PROJECT_ID}.iam.gserviceaccount.com

  # Create a secret on the Kubernetes cluster with the downloaded key
  # in the namespace the resources will reside (default in this case).
  kubectl --namespace default create secret generic google-cloud-key --from-file=key.json=cre-dataplane.json
fi