#!/bin/bash

DIR="$(dirname "$0")"
. "${DIR}/config"

set -v

# Reference:
# https://github.com/google/knative-gcp/blob/master/docs/install/pubsub-service-account.md

# Enable the Cloud Pub/Sub API on your project:
gcloud services enable pubsub.googleapis.com

# Create a new Service Account named cre-pubsub
gcloud iam service-accounts create cre-pubsub

# Give that Service Account the necessary permissions
# Note: You probably need something more fine-grained than roles/pubsub.editor
gcloud projects add-iam-policy-binding ${PROJECT_ID} \
  --member=serviceAccount:cre-pubsub@${PROJECT_ID}.iam.gserviceaccount.com \
  --role roles/pubsub.editor

if [ "$1" == "workload" ]; then
  echo "Workload identity, nothing to do"
else
  # Download a new JSON private key for that Service Account
  # Be sure not to check this key into source control!
  gcloud iam service-accounts keys create cre-pubsub.json \
  --iam-account=cre-pubsub@${PROJECT_ID}.iam.gserviceaccount.com

  # Create a secret on the Kubernetes cluster with the downloaded key
  # in the namespace the resources will reside (default in this case).
  kubectl --namespace default create secret generic google-cloud-key --from-file=key.json=cre-pubsub.json
fi