#!/bin/bash

set -v

DIR="$(dirname "$0")"
. "${DIR}/config"

# Install Serving CRDs
kubectl apply -f "https://github.com/knative/serving/releases/download/v${KNATIVE_SERVING_VERSION}/serving-crds.yaml"

# Install Serving Core Components
kubectl apply -f "https://github.com/knative/serving/releases/download/v${KNATIVE_SERVING_VERSION}/serving-core.yaml"

# Install Istio
kubectl apply -f "https://github.com/knative/net-istio/releases/download/v${KNATIVE_SERVING_VERSION}/istio.yaml"

# Install Knative Istio Controller
kubectl apply -f "https://github.com/knative/net-istio/releases/download/v${KNATIVE_SERVING_VERSION}/net-istio.yaml"

# Optional: Setup Magic DNS (xip.io)
kubectl apply -f "https://github.com/knative/serving/releases/download/v${KNATIVE_SERVING_VERSION}/serving-default-domain.yaml"

# Check Istio pods have STATUS 'Running'
# kubectl get pods -n istio-system

# Check Knative serving pods have STATUS 'Running'
# kubectl get pods -n knative-serving