#!/bin/bash

DIR="$(dirname "$0")"
. "${DIR}/config"

# Install Cloud Run Eventing CRDs
kubectl apply --selector events.cloud.google.com/crd-install=true \
-f "https://github.com/google/knative-gcp/releases/download/${KN_VERSION}/cloud-run-events.yaml"

# Install Cloud Run Eventing
kubectl apply \
-f "https://github.com/google/knative-gcp/releases/download/${KN_VERSION}/cloud-run-events.yaml"