#!/bin/bash

set -v

DIR="$(dirname "$0")"
. "${DIR}/config"

# Install latest Tekton Pipelines
kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/v${TEKTON_VERSION}/release.yaml

# Check pods have STATUS 'Running'
# kubectl get pods -n tekton-pipelines