#!/bin/bash

set -v

DIR="$(dirname "$0")"
. "${DIR}/config"

# Install Istio CRDs
kubectl apply -f "https://raw.githubusercontent.com/knative/serving/master/third_party/istio-${ISTIO_VERSION}/istio-crds.yaml"

# Install Istio
kubectl apply -f "https://raw.githubusercontent.com/knative/serving/master/third_party/istio-${ISTIO_VERSION}/istio-minimal.yaml"

# Check all Istio pods have STATUS 'Running'
# kubectl get pods -n istio-system