apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: trigger-event-display
spec:
  filter:
    attributes:
      type: dev.knative.sources.ping
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      #apiVersion: v1
      kind: Service
      name: event-display

